services:
  something:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pwn-something

    environment:
      - TERM=xterm

    ports:
      - "1317:1337"

    restart: unless-stopped